### ISSUE TITLE
chore!: APIキーの漏洩

### ISSUE THREAD

**Issue by shun-shobon** [kota-yata/HIYOSHI-Weather-Checker#1]
## 概要

こんにちは。
このプロジェクトに**重大な問題**があるため、報告させていただきます。

## 詳細

このプロジェクトではOpenWetherMapのAPIを使用しているようですが、そのAPIキーがスクリプト内にハードコーディングされており、リポジトリ内で管理されているため**一般に公開されています**。
本来、APIキーなどは**機密情報であり、一般には公開してはいけないものです。**
また、このプロジェクトは静的ホスティングだと思われますが、静的ホスティングの場合サーバーサイドでの処理が一切行われないため、**APIキーがクライアント側の手に渡ってしまい、同様にAPIキーの漏洩となってしまいます。**

対策としては、
- リポジトリからのAPIキーの消去(.envなどで環境変数として持っておく)
- サーバーサイドでの処理の追加(サーバーサイドで天気データをフェッチしてクライアントへ送信する)

などが挙げられます。

また、Gitの性質上一度commit / pushしてしまったデータを消去するのは大変難しいです。
残念ではありますが、このリポジトリは早めに消去してAPIキーの漏洩を防ぐことが重要です。

**Comment by kota-yata** [comment]
ご指摘ありがとうございます。APIキーを別ファイルにおいて.gitignoreに記載して解決しましたが、そこまで大切なリポジトリでもないため削除させていただきます。
